upstream gunicorn {
    server localhost:8000;
    keepalive 128;
}

server {
    listen 8080;
    client_max_body_size 4G;

    proxy_connect_timeout 120s;
    proxy_read_timeout 120s;
    proxy_http_version 1.1;
    server_name localhost;

    gzip on;
    gzip_min_length 1000;
    gzip_types font/woff2 text/css application/javascript application/json image/jpeg image/png;
    gzip_proxied no-cache no-store private expired auth;

    location / {
        proxy_pass http://gunicorn;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        aio threads;
    }
}

