# Generated by Django 4.1.7 on 2023-02-19 23:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('striked_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('vendor', models.TextField()),
            ],
        ),
    ]
